### ISSUE TITLE
IEでエラーが出て動かない

### ISSUE THREAD

**Issue by koya-iwasaki** [ktsn/vq#15]
@ktsn IE11で実行したところ、 `throw _iteratorError;` のところで `'Symbol' は定義されていません。` のエラーが出てしまい動きませんでした。
throw文を変えたほうがいいかもしれません。
http://uupaa.hatenablog.com/entry/2011/11/18/115409

**Comment by ktsn** [comment]
@koya-iwasaki 
v1.0.1 で修正しました。
IE では Symbol がサポートされていない && for-of を使っている のが原因でした。(おそらく)

**Comment by koya-iwasaki** [comment]
@ktsn 動きました。ありがとうございます。
