### ISSUE TITLE
Syntax for using only `progress`

### ISSUE THREAD

**Issue by bisquit** [ktsn/vq#7]
Would be convenient to have direct syntax for tween animation. Currently, it needs, 

```
vq(el, {}, opts).progress(func, [0, 1000])
```

Thanks

**Comment by ktsn** [comment]
@bisquit 
The special syntax will be introduced on v0.2.0.
It will be like the following example.

You can pass the progress callback to the 2nd arg or the value of `p`.

``` js
const swing = {
  p: (el, t, r, t0, tween) => {
    const offset = 100 * Math.sin(2 * tween * Math.PI);
    el[0].style.transform = `translate3d(${offset}px, 0, 0)`;
  },
  o: {
    duration: 1000,
    easing: 'easeOutCubic'
  }
}

vq(el, swing)
```

**Comment by qracker** [comment]
@ktsn 
Looks handy, thank you!

**Comment by bisquit** [comment]
@ktsn 
Looks handy, thank you!
